### ISSUE TITLE
Using it inside an ion-slider

### ISSUE THREAD

**Issue by RHinderiks** [leonardosalles/ionic2-zoom-area-example#2]
Hi,

I'm trying to use this component inside an ion-slide in ionic 3.9.2. However the moment i pinch the image disappears.

Also the slides within a modal so maybe it has some z-index issue ?

Could you look into this ?

**Comment by leonardosalles** [comment]
The components is not supported to be used inside ionic components, just ion-content. It is planned to the next release.
